version: "3.9"

services:
  backend:
    build: ./backend
    container_name: vr-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: vr-frontend
    ports:
      - "8080:8080"

    volumes:
      - ./frontend/assets:/usr/share/nginx/html/assets:ro
    depends_on:
      - backend



